# Generated by Django 5.1.3 on 2025-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
