# Generated by Django 5.1.3 on 2025-01-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='class_type',
            field=models.CharField(choices=[('group', 'Grupowe'), ('individual', 'Indywidualne')], default='group', max_length=20),
        ),
    ]
