name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 1. Zainstaluj zależności back-end
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install backend dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # 2. Uruchom testy Pythona (np. testy Django)
    - name: Run backend tests
      run: |
        python manage.py test

    # 3. Build front-end (o ile masz React)
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install front-end dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build front-end
      run: npm run build
      working-directory: ./frontend

    # 4. Uruchom testy front-end (np. npm test)
    - name: Run front-end tests
      run: npm test
      working-directory: ./frontend
