name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run containers
      run: |
        docker-compose build
        docker-compose up -d db  # uruchom kontener bazy
        docker-compose up -d web # ewentualnie
        # lub run test w kontenerze:
        docker-compose run web python manage.py test
